### PR TITLE
replacing momentjs with dayjs

### LINKED ISSUE #525: Replace 'moment.js' with 'dayjs'
**Is your feature request related to a problem? Please describe.**
`moment.js` is not even recommending itself anymore (see https://momentjs.com/docs/#/-project-status/).

**Describe the solution you'd like**
I personally had very good experience with day.js https://day.js.org/.
_Might also be more secure not sure though if any of them are a security threat._

**Describe alternatives you've considered**
[Luxon](https://moment.github.io/luxon/#/) - no experience
[date-fns](https://date-fns.org/) - not a fan (personally)
[js-joda](https://js-joda.github.io/js-joda/) - not a fan of java based to js projects

**Additional context**
image

### PR DESCRIPTION
**Pull request by bohn002**
Resolving #525 . Day.js is pretty much a drop in replacement with some minor changes. Example TS: [TS Day.js](https://day.js.org/docs/en/installation/typescript) 

For example after importing the base library you need to add any needed plugins and extend the base library, such as [UTC](https://day.js.org/docs/en/plugin/utc) or [RelativeTime](https://day.js.org/docs/en/customization/relative-time) for `.utc()` and `.fromNow()`

I did some quick searches but it didn't seem like there was a better way to import/extend multiple plugins in a single line. 

I did disagree with the suggested `import * as utc from "dayjs/plugin/utc";` and just truncated as more standard fare.

Largest deviation was setting [custom RelativeTime](https://day.js.org/docs/en/customization/relative-time) but it was roughly the same.

Hope this helps. Seemed to build fine and time stamps seemed to be working ok. Open to suggestions.

### CODE REVIEW

**Comment by Felix-Staud** [comment]
Without having tested it in action I can give the following feedback: 
Normally you don't want to extend dayjs ever single time multiple times with plugins/extensions.

What you do instead is in the main/root file you define all the necessary extensions. 

In this case it's probably the `index.js` file:

``` 
import { registerRootComponent } from "expo";
import dayjs from "dayjs";
import utcPlugin from "dayjs/plugin/utc";
import relativeTimePlugin from "dayjs/plugin/relativeTime";
import updateLocalePlugin from "dayjs/plugin/updateLocale";

import App from "./App";

dayjs.extend(utcPlugin);
dayjs.extend(relativeTimePlugin);
dayjs.extend(updateLocalePlugin);

// registerRootComponent calls AppRegistry.registerComponent('main', () => App);
// It also ensures that whether you load the app in Expo Go or in a native build,
// the environment is set up appropriately
registerRootComponent(App);
```

another approach is to move all these imports and `extend()` calls it into its own file and import that file into the `index.js` file (same result in the end).

That way you avoid importing files multiple times.

**Comment by Felix-Staud** [comment]
Your solutions is fine for me. Not exactly what I had in mind but fine for me.

I'll try again explaining what  I had in mind:
If you have a file (let's call it `dayJsInit.js`) that calls all the `dayjs.extend(...)` and this file is imported at the app entry level (index) you can still use the original dayjs (`import dayjs from "dayjs"`) as the root object will be extended with those plugins:

```ts
import { registerRootComponent } from "expo";

import App from "./App";
import "./path/to/initiDayJs"

// registerRootComponent calls AppRegistry.registerComponent('main', () => App);
// It also ensures that whether you load the app in Expo Go or in a native build,
// the environment is set up appropriately
registerRootComponent(App);

```

but like i said both is fine

**Comment by bohn002** [comment]
ok, i like your proposal better. less moving up-stack etc `.../../../../` Where should the dayjs init script live? `src/plugin`? Since its not really a component....

**Comment by Felix-Staud** [comment]
> ok, i like your proposal better. less moving up-stack etc `.../../../../` Where should the dayjs init script live? `src/plugin`? Since its not really a component....

For that we will have to wait for collaborators/maintainers to make a verdict 😁

**Comment by bohn002** [comment]
Okeydoke, thanks! I'll leave it where it is and see if folks have a better location suggestion then! thanks for the feedback.

**Review by sgriff96 — APPROVED** [review]
lgtm

**Comment by sgriff96** [comment]
> ok, i like your proposal better. less moving up-stack etc `.../../../../` Where should the dayjs init script live? `src/plugin`? Since its not really a component....

src/plugin works for me. We can always change later if needed.

**Comment by bohn002** [comment]
moved to src/plugins for now and updated index for new path.

**Comment by Felix-Staud** [comment]
@bohn002 mind fixing the tittle ? Minor inconvenience but it says datejs in it not dayjs

**Comment by bohn002** [comment]
Title fixed.

**Review by sgriff96 — CHANGES_REQUESTED** [review]
Just noticed this actually
CleanShot 2023-07-11 at 10 19 45@2x

**Comment by bohn002** [comment]
one snag with a minimal library is discovering plugins needed. Anymoo, added an additional plugin [AdvancedFormat](https://day.js.org/docs/en/plugin/advanced-format) and the ordinal displays correctly now.

image

**Comment by gkasdorf** [comment]
I think that's already addressed here. https://github.com/Memmy-App/memmy/pull/581

Do you know if the implementation in that PR will work with the changes made here?

**Comment by bohn002** [comment]
Should fold in just fine, the dayjs change was higher up a few lines. So assuming there isnt a github hiccup, should mesh

**Comment by Felix-Staud** [comment]
@gkasdorf consider merging this one first and looking into the other one to keep PRs in scope otherwise it gets messy really fast

**Review by gkasdorf — APPROVED** [review]
Looks fine to me. I'll review that other PR addressing the other issue to make sure it plays nice.

Thank you!

**Review by gkasdorf — APPROVED** [review]

**Pull request merged**
