### PR TITLE
replace account delete with logout and add it for last account too

### LINKED ISSUE #553: Account logout button
**Is your feature request related to a problem? Please describe.**
Once logged into an account you can't log out of it.

**Describe the solution you'd like**
A button to delete/logout of an existing account

**Describe alternatives you've considered**
Creating a duplicate account this being able to delete the existing one.

**Additional context**
image

### PR DESCRIPTION
**Pull request by Felix-Staud**
fixes #553

### CODE REVIEW

**Comment by sgriff96** [comment]
Do we wanna just add "Logout" for each account instead?

**Comment by Felix-Staud** [comment]
@sgriff96 i mean. Sure. Would make sense I guess. Cause we aren't deleting the accounts

**Comment by Felix-Staud** [comment]
It's now logout for all of them

**Review by gkasdorf — APPROVED** [review]
This seems fine to me.

**Pull request merged**
