### PR TITLE
Fix swipe to vote change throws you back to the root settings page (#810)

### LINKED ISSUE #810: [Bug]: swipe to vote switch triggers “back”
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

https://github.com/Memmy-App/memmy/assets/50131232/9be9159f-dbeb-4a2f-881a-6013dada4919

### Expected Behavior

The switch should change its state without sending you back

### Version

0.5 (3)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone 14

### PR DESCRIPTION
**Pull request by Felix-Staud**
### PR Creator Checklist

Ensure you've checked the following before submitting your PR:

- [X] You've discussed making your changes with a member of the dev team per contributing rules in the README
- [X] Your changes are free of any lint errors
- [X] Your changes are free of any typescript errors
- [X] You've tested your changes

### Summary

this fixes #810 

- fix the rerender upon swipeToVote change by buffering the change first 
- add todo notices for missing translations

### Screenshots

https://github.com/Memmy-App/memmy/assets/50131232/9295a5cc-1fe7-45fd-bf45-999727a7dbf0

### Test Plan

1. Go to `Settings` -> `Appearance`
2. Activate Swipe to Vote
3. Go to `Feed`
4. Try Voting by swiping a post -> should work
5. Go back to  `Settings` -> `Appearance`.
6. Deactivate Swipe to Vote
7. Go to `Feed` -> Can't swipe anymore but now you can use the fullscreen "go back" gesture instead

### CODE REVIEW

**Review by sgriff96 — CHANGES_REQUESTED** [review]
This doesn't behave very well since if you leave the settings page before the invisible buffer takes effect, it doesn't apply the settings.

**Comment by Felix-Staud** [comment]
> This doesn't behave very well since if you leave the settings page before the invisible buffer takes effect, it doesn't apply the settings.

You mean like when you are "super" fast with the switch and then instantly switch pages?

**Comment by sgriff96** [comment]
> You mean like when you are "super" fast with the switch and then instantly switch pages?

I didn't even try to be that fast, it was like pretty casual speed imo and still didn't take effect. I can record in a min.

**Comment by Felix-Staud** [comment]
> > You mean like when you are "super" fast with the switch and then instantly switch pages?
> 
> I didn't even try to be that fast, it was like pretty casual speed imo and still didn't take effect. I can record in a min.

I believe you like that, don't worry.
Gotta think of a better solution then :/

**Comment by Felix-Staud** [comment]
It should now get applied properly.

There is still the odd reload when changing its state and then clicking the back button in the header but I have no idea right now how to fix that as that settings affects the whole screen (all of them) due to that global gesture

**Comment by gkasdorf** [comment]
It was actually just that the whole stack was getting re-rendered on the change. I adjusted that here in this PR: https://github.com/Memmy-App/memmy/pull/823

I copied your changes over for the locale stuff though, since I had forgotten to do that.

**Pull request closed without merging**
