### PR TITLE
Oksolar Light Theme

### PR DESCRIPTION
**Pull request by Game-Warrior**
I have added and tested the [Oceanic Next](https://github.com/voronianski/oceanic-next-color-scheme) as well as the [Oksolar Light](https://meat.io/oksolar) Theme.
Simulator Screenshot - iPhone 14 Pro - 2023-07-03 at 10 53 03
Simulator Screenshot - iPhone 14 Pro - 2023-07-03 at 10 53 25

### CODE REVIEW

**Comment by sgriff96** [comment]
Hmmm Oceanic Next looks very similar to Oksolar Dark? Can you send screenshots of the two next to each other?

**Comment by Game-Warrior** [comment]
Sure! I change the accent color to further distinguish the two.
Simulator Screenshot - iPhone 14 Pro - 2023-07-03 at 19 07 46
Simulator Screenshot - iPhone 14 Pro - 2023-07-03 at 19 08 30

**Review by sgriff96 — CHANGES_REQUESTED** [review]
Hey can you refactor this to 1. have the correct properties for `IColors` and 2. remove the dark theme like we talked about? Also textPrimary and textSecondary should under no circumstance be the same color. We use those as separate colors for very important reasons in the app. 

Will review more after that but I can't even run the app because something got messed up I assume during merging:
```
const oceanicNextTheme = extendTheme({
  ...commonSettings,
  colors: {
    app: oceanicNextThemeColors,
```

**Comment by Game-Warrior** [comment]
I think I have fixed everything. Except for this lint error.

``` 
/home/runner/work/memmy/memmy/src/theme/theme.ts
Error:   15:[9](https://github.com/Memmy-App/memmy/actions/runs/5494750002/jobs/10013715905?pr=365#step:5:10)  error  Replace `⏎··lightThemeColors,·oksolarLightThemeColors⏎······` with `·lightThemeColors,·oksolarLightThemeColors`  prettier/prettier
```

**Comment by sgriff96** [comment]
Reviewing now

**Review by sgriff96 — APPROVED** [review]

**Pull request merged**
