### PR TITLE
implement i18next and add some example translations including german

### LINKED ISSUE #586: Internationalisation (i18n)
**Is your feature request related to a problem? Please describe.**
The app is currently based on pure english. Implementing i18n early on is recommended.

**Describe the solution you'd like**
https://docs.expo.dev/guides/localization/ uses i18n-js but also recommends using https://react.i18next.com/ 

**Describe alternatives you've considered**

i18n-js

**Additional context**
 n/a

### PR DESCRIPTION
**Pull request by Felix-Staud**
## PR Creator Checklist

Ensure you've checked the following before submitting your PR:

- [x] You've discussed making your changes with a member of the dev team per contributing rules in the README
- [x] Your changes are free of any lint errors
- [x] Your changes are free of any typescript errors
- [x] You've tested your changes

## Summary

It adds a general internationalisation (i18n) implementation that can be extended to the whole application. For now I've only translated a bit (english and german) for presentational purposes

## Test Plan

> If you want to check the application in german you either have to set your device to german or open the branch in your IDE and in `i18n.ts` add the `lng` property with `"de"` as value:

```ts
i18n
  .use(languageDetector)
  .use(initReactI18next)
  .init({
    resources: {
      en: {
        translation: english,
      },
      de: {
        translation: german,
      },
    },
    fallbackLng: "en",
    lng: "de",                      // <--------------------
    interpolation: {
      escapeValue: false, // react already safes from xss => https://www.i18next.com/translation-function/interpolation#unescape
    },
    compatibilityJSON: "v3",
  });

```

fixes #586

### CODE REVIEW

**Comment by ann0see** [comment]
In our project (jamulus.io) we use a web app for easier translation by the community. We use Hosted Weblate but I think there are others too.

**Comment by Felix-Staud** [comment]
@ann0see yeah I could see that in the future as i18next has support for that but 1 thing after another 😁

**Comment by gkasdorf** [comment]
This is great. Holding off on merging as you requested.

**Comment by gkasdorf** [comment]
@Felix-Staud Let me know whenever you think this is good to go. I tested it and it seems great!

**Comment by Felix-Staud** [comment]
@gkasdorf It's now ready to be merged.
Unfortunately a full fledged review will take forever but isn't that what a beta testing is for ? 👀

**Pull request merged**
