### PR TITLE
Store API tokens in Expo SecureStore instead of AsyncStorage

### PR DESCRIPTION
**Pull request by jderose9**
So, a few things worth mentioning...

1. I don't think the password needs to be stored, since the API token lives forever.

2. I took the approach that any existing accounts with API token stored in AsyncStorage should stay that way, rather than trying to convert them all over to SecureStore the next time they loaded or something. This did make the code a little more confusing as the account actions can't just blindly strip all the tokens on save and restore them all on load. Mostly this was because I was worried about some mistake or misunderstanding about how SecureStore works leaving working accounts in an invalid state. So, they don't get moved over to SecureStore unless they edit the account password or add a new account.

3. The characters permitted in the SecureStore key are limited, so I didn't have a great identifier (for instance, any path characters in a lemmy sever url would be invalid), so I generated a GUID for each account.

4. I'm not sure if there are any upcoming features that would require background access to the API. The default behavior of SecureStore is to only allow the value to be retrieved when the device is unlocked and is set on a per-key basis.

https://docs.expo.dev/versions/latest/sdk/securestore/#constants

5. I used a separate key for each account. I don't know what the upper limit on accounts someone might have is but that seemed safest (there's a 2048 byte limit per entry).

6. I don't really know if there's any way for the user to manage the SecureStore backing, like disabling it. And it seems like iCloud if enabled should handle both AsyncStorage and SecureStore/keychain stuff. So at this point I'm just treating this as a black box and assuming they will stay in sync, but I can research a little more.

Let me know if you think any of this needs be revised.. hope this helps.

### CODE REVIEW

**Comment by gkasdorf** [comment]
Awesome. I'll look this over later.

I agree on the password issue. My reasoning at first was that I was concerned there might be issues where authentication would need to be re-performed. I can probably take a look, but do you know off the top of your head if these JWT tokens expire? Regardless, we can implement logic for re-authentication if they do.

**Comment by jderose9** [comment]
From what I could tell when I looked into it last week, the JWT seems to never expire unless the password changes.

**Comment by Felix-Staud** [comment]
@gkasdorf @sgriff96 as this issue is considered `high priority` should we try to merge it before the big glue stack takes place ?

**Comment by gkasdorf** [comment]
@Felix-Staud sean is removing the password storage completely inside of the zustand migration.

**Pull request closed without merging**
